# Generated by Django 4.0.6 on 2022-07-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytypes',
            old_name='property_name',
            new_name='property_type_name',
        ),
    ]
