# Generated by Django 4.0.6 on 2022-07-12 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_types', '0002_rename_property_name_propertytypes_property_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.TextField()),
                ('details', models.TextField()),
                ('location', models.TextField()),
                ('sold', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=True)),
                ('property_size', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('property_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_types.propertytypes')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listed_properties.listedproperties')),
            ],
        ),
    ]
