# Generated by Django 4.0.6 on 2022-07-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listed_properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimages',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
