# Generated by Django 3.2 on 2022-09-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('title', models.TextField()),
                ('details', models.TextField()),
                ('location', models.TextField()),
                ('sold', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=True)),
                ('property_size', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('propertytypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_types.propertytypes')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listed_properties.listedproperties')),
            ],
        ),
    ]
