# Generated by Django 3.2 on 2022-07-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questrealty_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='rooms',
        ),
    ]
