# Generated by Django 3.2 on 2022-07-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questrealty_app', '0002_rename_room_message_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='rooms',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='names',
        ),
    ]
