# Generated by Django 3.2.14 on 2022-08-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questrealty_app', '0003_auto_20220825_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
